{'message': '\u30c7\u30d0\u30c3\u30af\u51fa\u529b', 'msg': '\u30c7\u30d0\u30c3\u30af\u51fa\u529b', 'created': 1626136124.572026, 'exc_text': None, 'processName': 'MainProcess', 'name': '__main__', 'msecs': 572.0260143280029, 'relativeCreated': 1.0030269622802734, 'module': 'basic3', 'levelname': 'DEBUG', 'funcName': '<module>', 'filename': 'basic3.py', 'threadName': 'MainThread', 'exc_info': None, 'lineno': 20, 'levelno': 10, 'args': (), 'process': 22424, 'thread': 17112, 'stack_info': None, 'pathname': 'c:/Users/200269/Documents/GitHub/python_code/logging/basic3.py'}(sctime)s - __main__ DEBUG -デバック出力
{'message': '\u60c5\u5831\u51fa\u529b', 'msg': '\u60c5\u5831\u51fa\u529b', 'created': 1626136124.5730233, 'exc_text': None, 'processName': 'MainProcess', 'name': '__main__', 'msecs': 573.0233192443848, 'relativeCreated': 2.0003318786621094, 'module': 'basic3', 'levelname': 'INFO', 'funcName': '<module>', 'filename': 'basic3.py', 'threadName': 'MainThread', 'exc_info': None, 'lineno': 21, 'levelno': 20, 'args': (), 'process': 22424, 'thread': 17112, 'stack_info': None, 'pathname': 'c:/Users/200269/Documents/GitHub/python_code/logging/basic3.py'}(sctime)s - __main__ INFO -情報出力
{'message': '\u8b66\u544a\u767a\u751f', 'msg': '\u8b66\u544a\u767a\u751f', 'created': 1626136124.5740247, 'exc_text': None, 'processName': 'MainProcess', 'name': '__main__', 'msecs': 574.0246772766113, 'relativeCreated': 3.001689910888672, 'module': 'basic3', 'levelname': 'WARNING', 'funcName': '<module>', 'filename': 'basic3.py', 'threadName': 'MainThread', 'exc_info': None, 'lineno': 22, 'levelno': 30, 'args': (), 'process': 22424, 'thread': 17112, 'stack_info': None, 'pathname': 'c:/Users/200269/Documents/GitHub/python_code/logging/basic3.py'}(sctime)s - __main__ WARNING -警告発生
{'message': '\u30a8\u30e9\u30fc\u767a\u751f', 'msg': '\u30a8\u30e9\u30fc\u767a\u751f', 'created': 1626136124.575027, 'exc_text': None, 'processName': 'MainProcess', 'name': '__main__', 'msecs': 575.0269889831543, 'relativeCreated': 4.004001617431641, 'module': 'basic3', 'levelname': 'ERROR', 'funcName': '<module>', 'filename': 'basic3.py', 'threadName': 'MainThread', 'exc_info': None, 'lineno': 23, 'levelno': 40, 'args': (), 'process': 22424, 'thread': 17112, 'stack_info': None, 'pathname': 'c:/Users/200269/Documents/GitHub/python_code/logging/basic3.py'}(sctime)s - __main__ ERROR -エラー発生
